apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhV3QxZEdsdU5qVTBNenBuYUhCZmNXNVVRVmREVVU5RGR6bGtTRmxKWVhwNWNqTnNOV2c1U205SVpqTkNNblZtWVcxeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
