apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  namespace: cinemaabyss
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image:  ghcr.io/ikutin6543/architecture-pro-cinemaabyss/events-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          env:
          - name: PORT
            value: "8082"
          - name: KAFKA_BROKERS
            value: "kafka:9092"
          envFrom:
          - configMapRef:
              name: cinemaabyss-config
          - secretRef:
              name: cinemaabyss-secrets
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /api/events/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/events/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events
  namespace: cinemaabyss
spec:
  selector:
    app: events
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP